### ISSUE TITLE
Website design concept

### ISSUE THREAD

**Issue by moeenio** [overcastchat/overcastchat.github.io#2]
https://invis.io/2RQTBX4XNQ6 Please click "13 comments" at the bottom-right

**Comment by moeenio** [comment]
@kyleplo

**Comment by kyleplo** [comment]
I really like this! I'm working on turning this into an HTML page: https://overcastchat.github.io/new

**Comment by moeenio** [comment]
> I really like this! I'm working on turning this into an HTML page: [overcastchat.github.io/new](https://overcastchat.github.io/new)

I would like to contribute to it when I will want to @kyleplo

**Comment by moeenio** [comment]
Here's the Gravit Designer source file, so you can get the icons : https://send.firefox.com/download/e0cb924eda/#so4f-LtnANo7jhTKM3Hzgg @kyleplo

**Comment by moeenio** [comment]
Closing for now, since the new website design is in place @kyleplo .
